"""create daily_summary table

Revision ID: 0c03cf01e9cb
Revises: 20738848a0e0
Create Date: 2026-01-07 15:57:32.172287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c03cf01e9cb'
down_revision: Union[str, None] = '20738848a0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summary',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('range_pct', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('low_bucket', sa.Integer(), nullable=False),
    sa.Column('high_bucket', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'trading_date', name='pk_daily_summary')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_summary')
    # ### end Alembic commands ###
